name: CI

on:
  push:
    branches: [ humble, jazzy, main ]
  pull_request:
    branches: [ humble, jazzy, main ]

jobs:
  ROS_CI:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          - jazzy
          - rolling
        include:
          # ROS 2 Humble Hawksbill
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
          # ROS 2 Jazzy Jalisco
          - docker_image: ubuntu:noble
            ros_distribution: jazzy
            ros_version: 2
          # ROS 2 Rolling Ridley
          - docker_image: ubuntu:noble
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup workspace
        run: mkdir -p ros_ws/src

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ros_ws/src

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Add pip break-system-packages for rosdep
        run: |
          printf "[install]\nbreak-system-packages = true\n" | sudo tee /etc/pip.conf

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        env:
          PIP_BREAK_SYSTEM_PACKAGES: "1"
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: "https://raw.githubusercontent.com/ROBOTIS-GIT/turtlebot3_machine_learning/main/turtlebot3_machine_learning_ci.repos"
          package-name: |
            turtlebot3_dqn
            turtlebot3_machine_learning
